name: DIANNCONVERT
description: A module to convert DIA report files to MSstats
keywords:
  - DIA-NN
  - conversion
  - MSstats
  - Triqler
tools:
  - custom:
      description: |
        A custom module for DIA-NN report file conversion.
      homepage: https://github.com/bigbio/quantms
      documentation: https://github.com/bigbio/quantms/tree/readthedocs
input:
  - report:
      type: file
      description: DIA-NN main report file
      pattern: "*.tsv"
  - exp_design:
      type: file
      description: An experimental design file including Sample and replicates column et al.
      pattern: "*.tsv"
output:
  - out_msstats:
      type: file
      description: MSstats input file
      pattern: "out_msstats.csv"
  - out_triqler:
      type: file
      description: Triqler input file
      pattern: "out_triqler.tsv"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
