# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-diaproteomics-1.2.4
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6.10
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - anaconda::openjdk=8.0.152
  - conda-forge::r-base=4.0.2
  - bioconda::openms-thirdparty=2.5.0
  - bioconda::pyprophet=2.1.4
  - conda-forge::networkx=2.4
  - bioconda::easypqp=0.1.8
  - conda-forge::r-rmsnumpress=1.0.1
  - conda-forge::r-magrittr=2.0.1
  - conda-forge::r-bit64=4.0.5
  - conda-forge::r-ape=5.4
  - conda-forge::r-phangorn=2.5.5
  - conda-forge::r-pracma=2.3.3
  - conda-forge::r-tidyr=1.1.2
  - conda-forge::r-dplyr=1.0.2
  - conda-forge::r-ggplot2=3.3.2
  - conda-forge::r-gplots=3.1.0
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-biocmanager=1.30.10
  - conda-forge::r-remotes=2.2.0
  - conda-forge::r-signal=0.7_6
  - conda-forge::r-dbi=1.1.0
  - conda-forge::r-gridextra=2.3
  - conda-forge::r-rcpp=1.0.5
  - conda-forge::r-rlang=0.4.10
  - conda-forge::r-rsqlite=2.2.1
  - conda-forge::r-scales=1.1.1
  - conda-forge::r-reticulate=1.18
  - conda-forge::r-zoo=1.8_8
  - conda-forge::r-remotes=2.2.0
  - bioconductor-MSstats=3.20.1
  - bioconductor-mzr=2.24.0
  - bioconductor-biocparallel=1.24.0
