repository_type: pipeline

lint:
  files_exist:
    - assets/multiqc_config.yml
  files_unchanged:
    - assets/email_template.html

update:
  nf-core/modules:
    samtools/sort: "1ad73f1b2abdea9398680d6d20014838135c9a35"
    samtools/index: "1ad73f1b2abdea9398680d6d20014838135c9a35"
