contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "GitHub issues"
    url: https://github.com/Clinical-Genomics-Laboratory/nf-cgl-cgs
    about: Create an issue on the GitHub repository to ask questions or report issues
