name: nf-core-coproid-1.1.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adapterremoval=2.3.1
  - blast=2.11.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - bowtie2=2.5.0
  - damageprofiler=0.4.9
  - fastqc=0.11.9
  - htslib=1.12
  - ipykernel=6.16.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - jupyter=1.0.0
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.11.2
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab_widgets=3.0.3
  - kraken2=2.1.2
  - make=4.3
  - markdown=3.2.1
  - multiqc=1.7
  - nbconvert=5.6.1
  - networkx=2.5.1
  - numpy=1.22.4
  - openjdk=11.0.8
  - pandas=1.5.1
  - pandocfilters=1.5.0
  - pip=22.3
  - plotnine=0.6.0
  - pmdtools=0.60
  - pysam=0.16.0.1
  - python=3.9.9
  - samtools=1.12
  - sed=4.8
  - sqlite=3.37.0
  - yaml=0.2.5
  - pip:
    - cachecontrol==0.12.11
    - cython==0.29.32
    - ete3==3.1.2
    - h5py==3.7.0
    - hdmedians==0.14.2
    - joblib==1.2.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - llvmlite==0.39.1
    - lockfile==0.12.2
    - matplotlib==3.5.3
    - msgpack==1.0.4
    - natsort==8.2.0
    - numba==0.56.3
    - pynndescent==0.5.8
    - pyyaml==5.4.1
    - scikit-bio==0.5.7
    - scikit-learn==1.1.3
    - scipy==1.8.1
    - sourcepredict==0.5
    - threadpoolctl==3.1.0
    - tqdm==4.64.1
    - umap-learn==0.5.3
    - pymdown-extensions==9.7