files_unchanged:
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows/linting.yml
  - assets/sendmail_template.txt
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE/bug_report.md
  - .gitignore
  - lib/NfcoreSchema.groovy
  - docs/README.md
files_exist:
  - .github/markdownlint.yml
  - bin/markdown_to_html.py
actions_awsfulltest: False
