# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-clipseq-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - conda-forge::pigz=2.3.4
  - conda-forge::perl=5.26.2

  # bioconda packages
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.9
  - bioconda::cutadapt=3.0
  - bioconda::bowtie2=2.4.2
  - bioconda::star=2.6.1d # Needs to be 2.6 to work with iGenomes indices
  - bioconda::samtools=1.11
  - bioconda::umi_tools=1.1.1
  - bioconda::bedtools=2.29.2
  - bioconda::subread=2.0.1
  - bioconda::preseq=2.0.3
  - bioconda::rseqc=4.0.0

  # peak calling packages - may need to switch to pip for latest versions
  - bioconda::icount=2.0.0
  - bioconda::paraclu=9
  - bioconda::pureclip=1.3.1
  - bioconda::piranha=1.2.1

  # motif calling packages
  - bioconda::meme=5.1.1
