name: nf-core-deepvariant-1.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=2.7.15
  - pip=10.0.1
  - deepvariant=0.7.0
  - picard=2.18.7
  - samtools=1.9
  - htslib=1.9
  - lbzip2=2.5
  - bzip2=1.0.6
