repository_type: pipeline
lint:
  actions_ci: False
  multiqc_config: False
  files_exist:
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/WorkflowOncoanalyser.groovy
nf_core_version: "2.14.1"
